### ISSUE TITLE
Vergadering 1 (20/2)

### ISSUE THREAD

**Issue by matt01y** [SELab-2/UGent-2#1]
# TODO tegen vergadering

- [x] Opgave lezen van klant
- 1 backend framework vinden die je wilt gebruiken
  - [x] 3 pros
  - [x] 3 cons
- [x] eens nadenken als je liever postgreSQL of SQLite wilt gebruiken.
- [x] emoji plaatsen op de discussie dinges dat bart vroeg.
- [x] in de onedrive een tablad in de excel aanmaken voor jouw tijden en ergens je naam invullen.
