### ISSUE TITLE
Oplijsting van nodige API endpoints backend

### ISSUE THREAD

**Issue by rvdkeere** [SELab-2/UGent-2#115]
Dit is een overview van de nodige aanpassingen aan de backend API zodat alle functionaliteit van de mockup ondersteund kan worden. Ik heb bij het onderzoeken van de huidige endpoints voornamelijk gekeken naar de docs van FastAPI op de main branch.
Sommige voorgestelde functies hebben meerdere mogelijke aanpakken of bevatten onduidelijkheden, die er telkens bij zijn vermeld.
Deze issue is bedoeld om te kunnen dienen als een checklist voor de ontwikkelaars van de backend API, en kan ook voor discussie gebruikt worden.
Plaats gerust een comment als je vragen of toevoegingen hebt.

Opmerking: alle routes beginnen in het echt natuurlijk met /api. Hier wordt al rekening gehouden met de naamsverandering "subject" naar "course".
De tekst kon niet renderen in een tasklist, dus ik heb een tasklist met enkel de nummers onderaan gezet.

1.
- `GET /student/projects/{project_id}/submission` : moet voor de groep van de huidige student-user de meest recente submission kunnen meegeven (dus success/failure/-, eventuele feedback, en uid of naam van de uploader).

2.
- `POST /student/projects/{project_id}/submission` Een endpoint om een submission in te dienen.

3.
- `GET /student/projects/{project_id}/group`: moet een lijst van groepsleden teruggeven.

4.
- `GET /student/projects/{project_id}/group/submission/file` : Het huidige ingediende bestand uit de databank doorsturen.

5.
- `POST /login/validate-token` zodat de frontend makkelijk kan achterhalen of de huidige login token nog geldig is.

6.
- `GET /courses/{course_id}/teachers`: Alle lesgevers opvragen die bij een bepaalde course horen.

7.
- `GET /projects/{project_id}/groups` moet het aantal users in elke groep meegeven, ofwel de lijst van user_ids zelf (als dit in de dataclass van groups zou zitten).

8.
- Optie 1: `POST /groups/{group_id}/members` : Een endpoint die een teacher toelaat om een student aan een bepaalde groep toe te voegen of te verwijderen.
Optie 2: dit kan ook met aparte `/.../members/add` en `/.../members/remove` endpoints.
Optie 3: zorg dat `/groups/{group_id}/join` dit ondersteunt, maar dat kan misschien een verwarrende naamgeving zijn dus stel ik een aparte endpoint voor. Gelieve hier nog duidelijk te maken welke aanpak van de drie je gekozen hebt.

9.
- `GET /groups/{group_id}/members` Zorg dat een teacher bij elke groep de namen van de studenten kan krijgen.

10.
- `GET /groups/{group_id}/submission`: Een endpoint voor teachers om van een bepaalde groep de recente indiening te zien (zonder het bestand zelf te downloaden).

11. `GET /groups/{group_id}/submission/file`: Zodat de teacher het bestand van een submission kan downloaden.

12.
- `PATCH /courses/{course_id}/projects` om dingen zoals deadline, archived en visible aan te kunnen passen. (Moet hierbij ook de docker file vervangen kunnen worden?)

- Bijkomend probleem:
Als de elementaire indieningsvoorwaarden (bvb folder layout) aangepast wordt, moeten alle huidige indieningen opnieuw gecheckt (en mogelijks als fout gemarkeerd of verwijderd) worden.

13.
- `GET /teacher/projects` om een lijst van alle projecten op te halen, net zoals bij student.
Hierbij is er in de mockup ook een veldje "# indieningen", dit kan ofwel in de backend al meegegeven worden voor elk project ofwel moet de frontend voor elk project alle groepen fetchen en dan nog eens voor elke groep het bestaan van een indiening nagaan.

14.
- (Een) endpoint(s) die een lijst met users horende bij een course toont zodat een teacher in staat is om 
   1. studenten in de course manueel aan groepen toe te voegen (zie 8.) 
   2. mede-lesgevers kan aanduiden of verwijderen (dit enkel door de maker van het vak?)
Deze twee functies kunnen ofwel afgeleid worden uit een algemene user lijst voor het vak
(optie 1: `/courses/{course_id}/users` dat zowel namen als rollen teruggeeft),
ofwel via twee verschillende endpoints
(optie 2: `/courses/{course_id}/students` en `/courses/{course_id}/teachers`).
- Onduidelijk: moet een teacher een lijst met alle andere teachers in de databank kunnen opvragen, zodat die teachers kan toevoegen aan het vak die er nog niet bij zitten? (zie managen lesgevers knop in de mockup)

15.
- `POST /courses/{course_id}/archive` om een vak te archiveren (is verwijderen ook een ding?)

16.
- Een vak verlaten: één methode voor zowel student als teacher (`POST /courses/{course_id}/leave`, optie 1) ofwel een aparte `POST teacher/courses/{course_id}/leave` en `POST teacher/courses/{course_id}/leave` (optie 2)  + algemeen: auto archiveer alles als de laatste teacher een vak verlaat, ofwel laat je dat niet toe.
- Optioneel: afhankelijk van de keuze hierboven, verander misschien ook `/student/courses/{course_id}/join` naar simpelweg `/courses/{course_id}/join` (optie 1), of alternatief behoud de huidige join link voor student en maak een teacher join link aan (optie 2).

```[tasklist]
### Tasks
- [x] 2. `POST /groups/{group_id}/submission`
- [x] 3. `GET /projects/{project_id}/group`
- [x] 5. `POST /login/validate-token`
- [x] 6. `GET /courses/{course_id}/teachers`
- [x] POST /groups/{group_id}/add en /groups/{group_id}/remove
- [x] 9. `GET /groups/{group_id}/members`
- [x] 10. `GET /groups/{group_id}/submission`
- [x] 11. `GET /groups/{group_id}/submission/file`
- [x] 12. `PUT /projects/{project_id}`
- [x] 13. `GET /teacher/projects`
- [x] 14. Kies eerst een aanpak.
- [x] 15. `PUT /courses/{course_id}`
- [x] 16. Kies eerst een aanpak.
```
