### ISSUE TITLE
Web design mockup

### ISSUE THREAD

**Issue by ruvdamme** [SELab-2/UGent-2#2]
```[tasklist]
### Tasks
- [x] Beslissen tool: [Pencil](http://pencil.evolus.vn/Default.html), [draw.io](http://www.draw.io/) of [Figma](https://www.figma.com/)   =>   **Figma**
- [x] Leren werken met de tool
- [x] View student pagina's
- [x] View student acties linken
- [x] View lesgever pagina's
- [x] View lesgever acties linken
- [x] Afwerking
```
