### ISSUE TITLE
Vergadering 11

### ISSUE THREAD

**Issue by cstefc** [SELab-2/UGent-2#251]
Aanwezigen: Ruben, Matthias, Lucas, Albéric, Mathieu, Emma, Robbe en Stef
Notulist: Stef

# Besproken punten
- Overlopen gedaan werk, extra uitleg bij de timesheets
- Geven rol leerkracht
- Allignment van titels
- Probleem aanmaken nieuw vak
- Statistieken leerkracht, welke?
- Verdelen van de unassigned issues (zie taakverdeling)

## [Probleem rol leerkachten oplossen](https://github.com/SELab-2/UGent-2/issues/246)
De rol leerkracht wordt nu bepaalt met een CAS attribute die niet vertrouwbaar genoeg is voor leerkrachten.
**Oplossing**: Standaard student; de admin promoveert de leerkrachten

## [Alligning titles](https://github.com/SELab-2/UGent-2/issues/225)
De title is gecentreerd in de balk en de tabel op de pagina, issue gesloten.

## [Probleem aanmaken nieuw vak](https://github.com/SELab-2/UGent-2/pull/243)
Na het aanmaken van een course; Is de lijst met leerkrachten leeg

## [Statistieken weergeven](https://github.com/SELab-2/UGent-2/issues/227)
- indiening status (percentage studenten elk)

# Taken verdeling
Ruben:
- [ ] [teacher home cards laden raar](https://github.com/SELab-2/UGent-2/issues/249)
- [ ] [Fix css voor deadline](https://github.com/SELab-2/UGent-2/issues/241)
- [ ] [frontend DEBUG environment variable](https://github.com/SELab-2/UGent-2/issues/237)
- [ ] [Intuitivere knoppen bij indiening](https://github.com/SELab-2/UGent-2/issues/216)
- [ ] [Simple submission test: global constraint en extension constraint](https://github.com/SELab-2/UGent-2/issues/214)
- [ ] [Dubbele knop wegdoen](https://github.com/SELab-2/UGent-2/issues/213)
- [ ] [Scrollbar in het midden van de startpagina](https://github.com/SELab-2/UGent-2/issues/203)
- [ ] [Kaartjes op homepagina van student moet clickable zijn](https://github.com/SELab-2/UGent-2/issues/187)

Matthias:
- [ ] [Join Course Page](https://github.com/SELab-2/UGent-2/issues/234)
- [ ] [Course delen als lesgever](https://github.com/SELab-2/UGent-2/issues/228)
- [ ] [Functionaliteiten implementeren](https://github.com/SELab-2/UGent-2/issues/191)
- [ ] [Geen errors tonen wanneer iemand op een pagina zit voor een andere role](https://github.com/SELab-2/UGent-2/issues/151)

Lukas:
- [ ] [Statistieken weergeven](https://github.com/SELab-2/UGent-2/issues/227)
- [ ] [Simple submission test: global constraint en extension constraint](https://github.com/SELab-2/UGent-2/issues/214)
- [ ] [Error handlers in app.py](https://github.com/SELab-2/UGent-2/issues/204)
- [ ] [Homepage leeg](https://github.com/SELab-2/UGent-2/issues/200)

Albéric:
- [ ] [Aanmaak nieuwe course, de persoon direct toevoegen als teacher](https://github.com/SELab-2/UGent-2/issues/239)

Mathieu:
- [ ] [Probleem rol leerkachten oplossen](https://github.com/SELab-2/UGent-2/issues/246)
- [ ] [Automatic deploy functie](https://github.com/SELab-2/UGent-2/issues/247)
- [ ] [Alle indieningen van project downloaden in backend](https://github.com/SELab-2/UGent-2/issues/224)
- [ ] [Automatic testing](https://github.com/SELab-2/UGent-2/issues/219)

Emma:
- [x] [Leave knop bij groepen](https://github.com/SELab-2/UGent-2/issues/244)
- [x] [Status ook invullen als er nog geen indiening is](https://github.com/SELab-2/UGent-2/issues/242)
- [x] [Na post request van een nieuw vak/project aanmaken redirect naar dit nieuw vak/project](https://github.com/SELab-2/UGent-2/issues/215)
- [ ] [Een student moet een groep kunnen joinen](https://github.com/SELab-2/UGent-2/issues/188)

Stef:
- [ ] [Filter functie voorzien](https://github.com/SELab-2/UGent-2/issues/248)
- [x] [Log user uit als de session token ongeldig is](https://github.com/SELab-2/UGent-2/issues/201)
- [ ] [Functionaliteiten implementeren](https://github.com/SELab-2/UGent-2/issues/191)

Robbe:
- [ ] [testen aanvullen in de frontend](https://github.com/SELab-2/UGent-2/issues/220)
- [ ] [Put frontend test in the GitHub actions](https://github.com/SELab-2/UGent-2/issues/199)
