### ISSUE TITLE
Eenvoudige Testen Indiening

### ISSUE THREAD

**Issue by lbarraga** [SELab-2/UGent-2#43]
Een indiening moet gestest kunnen worden op verschillende criteria. Met dit issue wil ik een aanzet geven tot het vastleggen van enkele simpele criteria:

```[tasklist]
### Tasks
- [x] Indiening is een bepaald bestand
- [x] Als de indiening een zip bestand is, moeten er bepaalde mappen/bestanden in aanwezig zijn
- [x] Als de indiening een zip bestand is mogen er bepaalde bestanden niet inzitten.
```
